POST http://localhost:8080/go/sha256
Content-Type: application/json

{
  "num1": "100",
  "num2": "10"
}

###
GET http://localhost:8080/go/write?lineNumber=99
Accept: application/json

### Server Response:
200 OK application/json
{
   "result": "corresponding result",
   "hasError": "false if there is no error else true"
}
